load 'bishop.rb'
load 'board.rb'
load 'cursor_module.rb'
load 'display.rb'
load 'inheritence.rb'
load 'king.rb'
load 'knight.rb'
load 'piece.rb'
load 'queen.rb'
load 'rook.rb'
load 'sliding_piece.rb'
load 'stepping_piece.rb'
board = Board.new
